### PR TITLE
Documentation: Minor updates in README.md

### PR DESCRIPTION
**Pull request by raoulbhatia**

### CODE REVIEW

**Comment by simontesar** [comment]
The KDK allows configuration of a Github user in `config.yaml`, but I'm not sure if that's actually a requirement or not.  It also explains in the README how to generate a key and add it to your account. Shouldn't we try to get as much of our users to use Github?

**Comment by dcwangmit01** [comment]
Left one comment.  The other line change is good.

**Comment by raoulbhatia** [comment]
I've removed 6b317482d1c4784b8d326cac03befc04f50f6824 (Clone from HTTPS URL) from this PR.

**Review by simontesar — APPROVED** [review]

**Review by darkyat — APPROVED** [review]

**Comment by raoulbhatia** [comment]
Minor change, only.

**Pull request merged**
